# Generated by Django 3.1.7 on 2021-03-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_game_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructorCredentials',
            new_name='Instructor',
        ),
        migrations.RenameModel(
            old_name='PlayerCredentials',
            new_name='Player',
        ),
    ]
