# Generated by Django 3.1.7 on 2021-03-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_game_backend', '0002_auto_20210321_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
